spring.application.name=shareit

spring.datasource.url=jdbc:mysql://localhost:8100/share_it?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Логирование SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Оптимизация
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.generate_statistics=false
