DELETE FROM bookings;
DELETE FROM items;
DELETE FROM users;
ALTER TABLE bookings AUTO_INCREMENT = 1;
ALTER TABLE items AUTO_INCREMENT = 1;
ALTER TABLE users AUTO_INCREMENT = 1;
OPTIMIZE TABLE bookings;
OPTIMIZE TABLE items;
OPTIMIZE TABLE users;