SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM comments;
DELETE FROM bookings;
DELETE FROM items;
DELETE FROM users;

ALTER TABLE comments AUTO_INCREMENT = 1;
ALTER TABLE bookings AUTO_INCREMENT = 1;
ALTER TABLE items AUTO_INCREMENT = 1;
ALTER TABLE users AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;